var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/auth/signin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12fp68-._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_04zd0ba.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fo5s5x._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/_0x.mfq.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_auth_signin_page_actions_0wiyxay.js")
R.m(98942)
module.exports=R.m(98942).exports
