var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/drivers/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j7qo_r._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_086nq2r.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fo5s5x._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ppctuh._.js")
R.c("server/chunks/ssr/_0x.mfq.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_0efws96._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_drivers_page_actions_10dv.7_.js")
R.m(68584)
module.exports=R.m(68584).exports
